import { User, Subscription, AppNotification, Role, SubRole } from './types';
import { add, formatISO } from 'date-fns';

const today = new Date();

export const mockUsers: User[] = [
  // POCs (Point of Contact)
  { id: 'user-1', name: 'Alice Smith', email: 'alice@example.com', password: 'password', role: 'poc', subrole: null, department: 'Marketing' },
  { id: 'user-2', name: 'Bob Johnson', email: 'bob@example.com', password: 'password', role: 'poc', subrole: null, department: 'Engineering' },
  {id: 'user-8', name: 'abc', email: 'abc@example.com', password: 'password', role: 'poc', subrole: null, department: 'IT' },
  
  // HODs
  { id: 'user-3', name: 'Charles Brown (HOD)', email: 'charles@example.com', password: 'password', role: 'hod', isHOD: true, subrole: null, department: 'Marketing' },
  { id: 'user-4', name: 'Diana Prince (HOD)', email: 'diana@example.com', password: 'password', role: 'hod', isHOD: true, subrole: null, department: 'Engineering' },

  // Finance
  { id: 'user-5', name: 'Ethan Hunt (APA)', email: 'ethan@example.com', password: 'password', role: 'finance', subrole: 'apa', department: 'Marketing' },
  { id: 'user-6', name: 'Fiona Glenanne (AM)', email: 'fiona@example.com', password: 'password', role: 'finance', subrole: 'am', department: 'Finance' },


];

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub-1',
    toolName: 'Figma',
    vendorName: 'Figma Inc.',
    duration: 12,
    cost: 1440,
    department: 'Engineering',
    purpose: 'For UI/UX design and collaboration.',
    status: 'Active',
    requestedBy: 'user-2',
    requestDate: formatISO(add(today, { months: -6 })),
    hodId: 'user-4',
    expiryDate: formatISO(add(today, { months: 6 })),
    approvedBy: 'user-4',
    paidBy: 'user-5',
    paymentDate: formatISO(add(today, { months: -6, days: 2 })),
  },
  {
    id: 'sub-2',
    toolName: 'Canva Pro',
    vendorName: 'Canva',
    duration: 12,
    cost: 1200,
    department: 'Marketing',
    purpose: 'Creating marketing materials and social media posts.',
    status: 'Active',
    requestedBy: 'user-1',
    requestDate: formatISO(add(today, { months: -2 })),
    hodId: 'user-3',
    expiryDate: formatISO(add(today, { months: 10 })),
    approvedBy: 'user-3',
    paidBy: 'user-5',
    paymentDate: formatISO(add(today, { months: -2, days: 2 })),
  },
  {
    id: 'sub-3',
    toolName: 'ChatGPT Plus',
    vendorName: 'OpenAI',
    duration: 12,
    cost: 240,
    department: 'Engineering',
    purpose: 'AI-assisted coding, documentation, and content generation.',
    status: 'Active',
    requestedBy: 'user-2',
    requestDate: formatISO(add(today, { months: -3 })),
    hodId: 'user-4',
    expiryDate: formatISO(add(today, { months: 9 })),
    approvedBy: 'user-4',
    paidBy: 'user-5',
    paymentDate: formatISO(add(today, { months: -3, days: 1 })),
  },
  {
    id: 'sub-4',
    toolName: 'Claude Pro',
    vendorName: 'Anthropic',
    duration: 12,
    cost: 240,
    department: 'Engineering',
    purpose: 'Advanced AI assistant for code analysis and technical writing.',
    status: 'Active',
    requestedBy: 'user-2',
    requestDate: formatISO(add(today, { months: -2 })),
    hodId: 'user-4',
    expiryDate: formatISO(add(today, { months: 10 })),
    approvedBy: 'user-4',
    paidBy: 'user-5',
    paymentDate: formatISO(add(today, { months: -2, days: 1 })),
  },
  {
    id: 'sub-5',
    toolName: 'Lovable',
    vendorName: 'Lovable.dev',
    duration: 6,
    cost: 1200,
    department: 'Engineering',
    purpose: 'AI-powered full-stack development platform.',
    status: 'Active',
    requestedBy: 'user-2',
    requestDate: formatISO(add(today, { months: -1 })),
    hodId: 'user-4',
    expiryDate: formatISO(add(today, { months: 5 })),
    approvedBy: 'user-4',
    paidBy: 'user-5',
    paymentDate: formatISO(add(today, { months: -1, days: 1 })),
  },
  {
    id: 'sub-6',
    toolName: 'GitHub Copilot',
    vendorName: 'GitHub',
    duration: 12,
    cost: 1200,
    department: 'Engineering',
    purpose: 'AI pair programming and code completion.',
    status: 'Active',
    requestedBy: 'user-2',
    requestDate: formatISO(add(today, { months: -4 })),
    hodId: 'user-4',
    expiryDate: formatISO(add(today, { months: 8 })),
    approvedBy: 'user-4',
    paidBy: 'user-5',
    paymentDate: formatISO(add(today, { months: -4, days: 2 })),
  },
  {
    id: 'sub-7',
    toolName: 'Notion Team',
    vendorName: 'Notion Labs',
    duration: 12,
    cost: 960,
    department: 'Engineering',
    purpose: 'Project management, documentation, and knowledge base.',
    status: 'Active',
    requestedBy: 'user-2',
    requestDate: formatISO(add(today, { months: -5 })),
    hodId: 'user-4',
    expiryDate: formatISO(add(today, { months: 7 })),
    approvedBy: 'user-4',
    paidBy: 'user-5',
    paymentDate: formatISO(add(today, { months: -5, days: 1 })),
  },
  {
    id: 'sub-8',
    toolName: 'Slack Business+',
    vendorName: 'Slack Technologies',
    duration: 12,
    cost: 1500,
    department: 'Marketing',
    purpose: 'Team communication and collaboration.',
    status: 'Pending',
    requestedBy: 'user-1',
    hodId: 'user-3',
    requestDate: formatISO(add(today, { days: -3 })),
  },
  {
    id: 'sub-9',
    toolName: 'Zoom Meetings Pro',
    vendorName: 'Zoom Video Communications',
    duration: 12,
    cost: 1800,
    department: 'Marketing',
    purpose: 'For client meetings, webinars, and team calls.',
    status: 'Active',
    requestedBy: 'user-1',
    requestDate: formatISO(add(today, { months: -1 })),
    hodId: 'user-3',
    expiryDate: formatISO(add(today, { days: 8 })), // Expiring soon
    approvedBy: 'user-3',
    paidBy: 'user-5',
    paymentDate: formatISO(add(today, { months: -1, days: 2 })),
  },
  {
    id: 'sub-10',
    toolName: 'Adobe Creative Cloud',
    vendorName: 'Adobe Inc.',
    duration: 12,
    cost: 7200,
    department: 'Marketing',
    purpose: 'Professional design tools (Photoshop, Illustrator, Premiere Pro).',
    status: 'Active',
    requestedBy: 'user-1',
    requestDate: formatISO(add(today, { months: -8 })),
    hodId: 'user-3',
    expiryDate: formatISO(add(today, { months: 4 })),
    approvedBy: 'user-3',
    paidBy: 'user-5',
    paymentDate: formatISO(add(today, { months: -8, days: 3 })),
  },
  {
    id: 'sub-11',
    toolName: 'Miro',
    vendorName: 'Miro',
    duration: 12,
    cost: 1200,
    department: 'Engineering',
    purpose: 'Visual collaboration and online whiteboarding.',
    status: 'Active',
    requestedBy: 'user-2',
    requestDate: formatISO(add(today, { months: -3 })),
    hodId: 'user-4',
    expiryDate: formatISO(add(today, { months: 9 })),
    approvedBy: 'user-4',
    paidBy: 'user-5',
    paymentDate: formatISO(add(today, { months: -3, days: 2 })),
  },
  {
    id: 'sub-12',
    toolName: 'Linear',
    vendorName: 'Linear',
    duration: 12,
    cost: 960,
    department: 'Engineering',
    purpose: 'Issue tracking and project management.',
    status: 'Approved',
    requestedBy: 'user-2',
    requestDate: formatISO(add(today, { days: -2 })),
    hodId: 'user-4',
    approvedBy: 'user-4',
    approvalDate: formatISO(add(today, { days: -1 })),
  },
  {
    id: 'sub-13',
    toolName: 'Grammarly Business',
    vendorName: 'Grammarly',
    duration: 12,
    cost: 1800,
    department: 'Marketing',
    purpose: 'Writing assistance and grammar checking.',
    status: 'Active',
    requestedBy: 'user-1',
    requestDate: formatISO(add(today, { months: -6 })),
    hodId: 'user-3',
    expiryDate: formatISO(add(today, { months: 6 })),
    approvedBy: 'user-3',
    paidBy: 'user-5',
    paymentDate: formatISO(add(today, { months: -6, days: 1 })),
  },
  {
    id: 'sub-14',
    toolName: 'Loom Business',
    vendorName: 'Loom',
    duration: 12,
    cost: 1200,
    department: 'Marketing',
    purpose: 'Video recording and screen sharing for async communication.',
    status: 'Active',
    requestedBy: 'user-1',
    requestDate: formatISO(add(today, { months: -4 })),
    hodId: 'user-3',
    expiryDate: formatISO(add(today, { months: 8 })),
    approvedBy: 'user-3',
    paidBy: 'user-5',
    paymentDate: formatISO(add(today, { months: -4, days: 2 })),
  },
  {
    id: 'sub-15',
    toolName: 'Vercel Pro',
    vendorName: 'Vercel',
    duration: 12,
    cost: 2400,
    department: 'Engineering',
    purpose: 'Web hosting, deployment, and serverless functions.',
    status: 'Active',
    requestedBy: 'user-2',
    requestDate: formatISO(add(today, { months: -7 })),
    hodId: 'user-4',
    expiryDate: formatISO(add(today, { months: 5 })),
    approvedBy: 'user-4',
    paidBy: 'user-5',
    paymentDate: formatISO(add(today, { months: -7, days: 1 })),
  },
];

export const mockNotifications: AppNotification[] = [
    { 
        id: 'notif-1', 
        userId: 'user-1', 
        message: 'Your request for Slack has been submitted for approval.', 
        isRead: true, 
        createdAt: formatISO(add(today, { days: -3 })),
    },
    { 
        id: 'notif-2', 
        userId: 'user-2', 
        message: 'Your request for ChatGPT has been approved and is pending payment.', 
        isRead: false, 
        createdAt: formatISO(add(today, { days: -1 })),
    },
    { 
        id: 'notif-3', 
        userId: 'user-4', 
        message: 'A new subscription request for ChatGPT is awaiting your approval.', 
        isRead: true, 
        createdAt: formatISO(add(today, { days: -2 })),
    },
    { 
        id: 'notif-4', 
        userId: 'user-3', 
        message: 'Your department’s subscription for Zoom is expiring in 8 days.', 
        isRead: false, 
        createdAt: formatISO(add(today, { days: -2 })),
    },
];
